export interface Language {
  code: string;
  name: string;
  flag: string;
}

export interface ServiceCard {
  id: string;
  title: string;
  description: string;
  image: string;
  features: string[];
}

export interface Statistic {
  id: string;
  value: number;
  label: string;
  suffix?: string;
  prefix?: string;
}

export interface ContactFormData {
  name: string;
  email: string;
  phone?: string;
  subject: string;
  message: string;
}

export interface TeamMember {
  id: string;
  name: string;
  position: string;
  image: string;
  bio: string;
}

export interface TradeFair {
  id: string;
  name: string;
  location: string;
  date: string;
  description: string;
}

export type TranslationKeys = 
  | 'nav.home'
  | 'nav.services'
  | 'nav.about'
  | 'nav.contact'
  | 'hero.title'
  | 'hero.subtitle'
  | 'hero.cta'
  | 'hero.learnMore'
  | 'services.title'
  | 'services.subtitle'
  | 'statistics.title'
  | 'statistics.subtitle'
  | 'statistics.reliability'
  | 'statistics.reliability.description'
  | 'statistics.safety'
  | 'statistics.safety.description'
  | 'statistics.coverage'
  | 'statistics.coverage.description'
  | 'about.title'
  | 'about.hero.title'
  | 'about.hero.subtitle'
  | 'about.hero.cta'
  | 'about.hero.stat1'
  | 'about.hero.stat2'
  | 'about.hero.stat3'
  | 'about.hero.cta'
  | 'about.company.title'
  | 'about.company.story'
  | 'about.company.paragraph1'
  | 'about.company.paragraph2'
  | 'about.mission.title'
  | 'about.mission.text'
  | 'about.vision.title'
  | 'about.vision.text'
  | 'about.values.title'
  | 'about.team.title'
  | 'about.team.description'
  | 'about.team.member1.position'
  | 'about.team.member1.bio'
  | 'about.team.member2.position'
  | 'about.team.member2.bio'
  | 'about.team.member3.position'
  | 'about.team.member3.bio'
  | 'about.team.member4.position'
  | 'about.team.member4.bio'
  | 'about.team.member5.position'
  | 'about.team.member5.bio'
  | 'about.team.member6.position'
  | 'about.team.member6.bio'
  | 'about.team.joinTeam.title'
  | 'about.team.joinTeam.description'
  | 'about.team.joinTeam.button'
  | 'about.tradeFairs.title'
  | 'about.tradeFairs.description'
  | 'about.tradeFairs.upcoming'
  | 'about.tradeFairs.recent'
  | 'about.tradeFairs.learnMore'
  | 'about.tradeFairs.cta.title'
  | 'about.tradeFairs.cta.description'
  | 'about.tradeFairs.cta.button'
  | 'about.working.title'
  | 'about.working.description'
  | 'about.working.benefits.title'
  | 'about.working.process.title'
  | 'about.working.solutions.title'
  | 'about.working.cta.title'
  | 'about.working.cta.description'
  | 'about.working.cta.getStarted'
  | 'about.working.cta.callNow'
  | 'about.working.benefits.reliablePartnership.title'
  | 'about.working.benefits.reliablePartnership.description'
  | 'about.working.benefits.support24.title'
  | 'about.working.benefits.support24.description'
  | 'about.working.benefits.qualityAssurance.title'
  | 'about.working.benefits.qualityAssurance.description'
  | 'about.working.benefits.provenTrackRecord.title'
  | 'about.working.benefits.provenTrackRecord.description'
  | 'about.working.process.step1.title'
  | 'about.working.process.step1.description'
  | 'about.working.process.step2.title'
  | 'about.working.process.step2.description'
  | 'about.working.process.step3.title'
  | 'about.working.process.step3.description'
  | 'about.working.process.step4.title'
  | 'about.working.process.step4.description'
  | 'about.working.partnerships.title'
  | 'about.working.partnerships.sme.title'
  | 'about.working.partnerships.sme.description'
  | 'about.working.partnerships.sme.feature1'
  | 'about.working.partnerships.sme.feature2'
  | 'about.working.partnerships.sme.feature3'
  | 'about.working.partnerships.sme.feature4'
  | 'about.working.partnerships.enterprise.title'
  | 'about.working.partnerships.enterprise.description'
  | 'about.working.partnerships.enterprise.feature1'
  | 'about.working.partnerships.enterprise.feature2'
  | 'about.working.partnerships.enterprise.feature3'
  | 'about.working.partnerships.enterprise.feature4'
  | 'about.working.partnerships.ecommerce.title'
  | 'about.working.partnerships.ecommerce.description'
  | 'about.working.partnerships.ecommerce.feature1'
  | 'about.working.partnerships.ecommerce.feature2'
  | 'about.working.partnerships.ecommerce.feature3'
  | 'about.working.partnerships.ecommerce.feature4'
  | 'about.certifications.title'
  | 'about.certifications.iso9001'
  | 'about.certifications.iso9001.description'
  | 'about.certifications.iso14001'
  | 'about.certifications.iso14001.description'
  | 'about.certifications.gdpr'
  | 'about.certifications.gdpr.description'
  | 'about.certifications.adr'
  | 'about.certifications.adr.description'
  | 'about.tradeFairs.eventGallery'
  | 'about.tradeFairs.completedBadge'
  | 'about.tradeFairs.upcomingBadge'
  | 'services.roadTransport.title'
  | 'services.roadTransport.description'
  | 'services.roadTransport.feature1'
  | 'services.roadTransport.feature2'
  | 'services.roadTransport.feature3'
  | 'services.roadTransport.feature4'
  | 'services.logistics.title'
  | 'services.logistics.description'
  | 'services.logistics.feature1'
  | 'services.logistics.feature2'
  | 'services.logistics.feature3'
  | 'services.logistics.feature4'
  | 'services.international.title'
  | 'services.international.description'
  | 'services.international.feature1'
  | 'services.international.feature2'
  | 'services.international.feature3'
  | 'services.international.feature4'
  | 'services.express.title'
  | 'services.express.description'
  | 'services.express.feature1'
  | 'services.express.feature2'
  | 'services.express.feature3'
  | 'services.express.feature4'
  | 'services.specialized.title'
  | 'services.specialized.description'
  | 'services.specialized.feature1'
  | 'services.specialized.feature2'
  | 'services.specialized.feature3'
  | 'services.specialized.feature4'
  | 'services.consulting.title'
  | 'services.consulting.description'
  | 'services.consulting.feature1'
  | 'services.consulting.feature2'
  | 'services.consulting.feature3'
  | 'services.consulting.feature4'
  | 'about.values.reliability.title'
  | 'about.values.reliability.description'
  | 'about.values.punctuality.title'
  | 'about.values.punctuality.description'
  | 'about.values.globalReach.title'
  | 'about.values.globalReach.description'
  | 'about.values.customerCare.title'
  | 'about.values.customerCare.description'
  | 'about.values.excellence.title'
  | 'about.values.excellence.description'
  | 'about.values.innovation.title'
  | 'about.values.innovation.description'
  | 'contact.title'
  | 'contact.subtitle'
  | 'contact.getInTouch'
  | 'contact.description'
  | 'contact.phone'
  | 'contact.email'
  | 'contact.address'
  | 'contact.hours'
  | 'contact.response'
  | 'contact.form.fullName'
  | 'contact.form.email'
  | 'contact.form.phone'
  | 'contact.form.subject'
  | 'contact.form.message'
  | 'contact.form.fullNamePlaceholder'
  | 'contact.form.emailPlaceholder'
  | 'contact.form.phonePlaceholder'
  | 'contact.form.subjectPlaceholder'
  | 'contact.form.messagePlaceholder'
  | 'contact.form.send'
  | 'contact.form.subjects.other'
  | 'footer.description'
  | 'footer.quickLinks'
  | 'footer.services'
  | 'footer.contactInfo'
  | 'footer.rights'
  | 'footer.address'
  | 'footer.phone'
  | 'footer.email'
  | 'stats.yearsExperience'
  | 'stats.happyClients'
  | 'stats.vehicles'
  | 'footer.addressLine1'
  | 'footer.addressLine2'
  | 'stats.countries';

export interface NavItem {
  key: TranslationKeys;
  href: string;
}
